### ISSUE TITLE
Titles are cut off too early

### ISSUE THREAD

**Issue by NoelleTGS** [MinnDevelopment/fxreddit#104]
Post titles over a certain length get cut off partway through. Reddit's title character limit should prevent any absurdly long titles so if possible, they shouldn't be cut off.

![Screenshot_20241223-173604.png](https://github.com/user-attachments/assets/bb910924-3f5b-4224-8b92-326af024c293)

**Comment by MinnDevelopment** [comment]
Discord is cutting them off.

**Comment by MinnDevelopment** [comment]
Small update: I've switched the structure of the embed to use the `twitter:creator` for the post title, which discord gives more room for. This should allow much longer titles to be visible.

![Image](https://github.com/user-attachments/assets/6274218a-a85e-4e45-ba0d-1b88b31684dc)
