### ISSUE TITLE
Doesn't seem to work with Telegram

### ISSUE THREAD

**Issue by ZornTaov** [MinnDevelopment/fxreddit#52]
https://rxddit.com/r/virtualreality/comments/19dpmuf/spatial_vacuuming/ this link works on discord, embedding as a video, but on telegram it shows up as the usual reddit watermarked embed preview image like it would with a regular reddit link.

**Comment by MinnDevelopment** [comment]
I'm open for a PR to make this happen.

**Comment by pwall2222** [comment]
Maybe if you remove https://github.com/MinnDevelopment/fxreddit/blob/ebd68f3cbbddac921b4952f69c84b099493fcada/src/endpoints/post.ts#L34 this line it would work on Telegram, since fxtwitter doesn't have the `<meta http-equiv="Refresh" content="0; URL=[url]">`
And it works fine in Telegram.
@MinnDevelopment

**Comment by sjain882** [comment]
https://github.com/dylanpdx/vxReddit this one works with telegram!

**Comment by MinnDevelopment** [comment]
I've removed the http equiv meta tag, does that resolve this issue?

**Comment by sjain882** [comment]
![Screenshot_20240922_142832_Nagram~2](https://github.com/user-attachments/assets/405c1122-9aeb-43f4-a733-7c4a2edd8cea)

https://www.rxddit.com/r/london/comments/1fllaua/certified_tfl_moment/

Seems to work with sound, yes. As for the varying formats and full audio support with those, will probably need more testing. Thanks for the update!

**Comment by MinnDevelopment** [comment]
Audio support is limited, since Reddit doesn't generally provide videos with audio. And since this is hosted on Cloudflare workers, re-encoding videos is not possible.

If you encounter any specific issues besides missing audio, feel free to open a new issue.
