### ISSUE TITLE
/:id path has stopped functioning 

### ISSUE THREAD

**Issue by ahs3n** [MinnDevelopment/fxreddit#79]
Now it redirects to www.reddit.com/:id, which does not work. And the preview does not exist at all. 

Possible fix: redd.it/:id can be the redirect target for the user? but I don’t know about how the embed system works though

**Comment by MinnDevelopment** [comment]
This should be resolved now

**Comment by ahs3n** [comment]
Can confirm, it is now working as expected.

**Comment by MinnDevelopment** [comment]
The short link was resolving to `www.reddit.com/id` instead of `redd.it/id`, I've adjusted the resolver logic to account for this
